<?php
/**
 * @author: syed ashraf ullah
 * date: 30/04/2020
 * problem: https://www.hackerrank.com/challenges/palindrome-index/problem
 * 
 */
/// Todo: Not passed 100% test case. Will solve it later.

// Complete the palindromeIndex function below.
function palindromeIndex($s) {
    $s = str_split($s);

    // $isPossible = isPalindromeString($s);
    // if (!$isPossible) return -1;

    $size = sizeof($s);
    
    for ($i=0, $j=$size-1; $i < $size/2; $i++,$j--) { 

        if ($s[$i] != $s[$j]) {
            if ($s[$i+1] == $s[$i]) {
                return $j;
            }
            return $i;
        }
    }

    return -1;
}

/**
 * Sample #1
 */
// $s = 'aaab';
$s = 'ijfyrvmkioryptjxuykvvmaeplcbgihprpqknewvuoukiejeetcciegxpkbvtlnnbhxqlwminjuwogdubhyllimdspbmbpdeydukbjuotpniwsfacelpmasiqwwtoaynevafguvakkkjfpjivxxjxttoqqlfrksvgudopyoclymrqxanvxyurslkjwpdjkysfchwewapxohrmjflkgieyvpkthofspxxuixyhxofoyydkeoukwaltrypynwrfxsagqynqqufruicyaxmyaauryksokluiguowwcppwwhthjthjihlicfkpyyamvisryrqbhgaepulbqvlbfylhfvygxbutlnnkhgnqmowclkeegrflssvarwgpyblmqaxxilqvcnapygthabvtuttmqdergpfxrfxbsryxfbngkkqmnmgkidybidvovdopipqdjrbovpxgcospdcblhcopgkgenxtvpnayfdndunjwefphhsuoukgdumhlmejcrlbyprdkfmkktatburrrcxvynfkcjufbggdvagjgutspvosqglkklgkbmuexrjayrdwslibgcvxakrstdeeqkosymwxegafaffuqnvystxsfpmbuqfldwedjbdpjdxmidhbsealxxhfptimmoyplfswhxmsbmflrnmltnytngceakqmbrfmxajhyyaalimexyrroqndxpjadcpeuuruudcveewsolwmmqgehuhhmsipwxutuoortsoyxnrmbqcnhitqfbysvhithdnetfvoxmnxahnbxprhalxgpwynghhpnxthdsvbflcgspjqfdafryljxkwhuhwihtrkmqnrcpavhmomrpujqguotsxqcvyjrsvejlxmebklnybhqvrjeoyxhyolupwolssuhtjlwvymxatovnybdabmysywkvlvrhtydfmaclmamgokuplxrpkrilqukcrclndospqubdupmmbheohwetqoihksleuxrxokpgisjdjvrmfwbotilkwttjofplfhluubbdtmidldpsatkvcvibrclijbtplfkignnccxinbajdttyxrjalnntxqnpesambpadrylicmrgglhffthqhukflxuqswftogwjhjrlxlteyclevsudpflefiwxictwkqitcagclajkeuqcqligstmxejxoormyluvpxeslecylypnpevywrnxwxvloqapexltxpolwqkisdxkhulgmaeladaotcexcstcijohcyrucqilntsctyovcqkxurxamscweqfiswgwpojdiegfdwbgpogkifkuanregwoywuwojgsumbapxdxntfacmlwmbrsjohjndgdooxjbylswrrmlymonancbfunwewmjfpytpkwoyrlqlacknsanhcrowfnecbnjsofjccxbvmtimvsartqbxkpvpecthpdahijlmioiwisjgmmxifbgptefagbhyghiqrtfcinbsjmyvyaggbovuvdueeefmmndgjiktylmiaogcqoitffrbkogptneicionsbirowconiqgwabfhsgrhojbdojhyaurdfkrfojuxacwcdcjxlcfanjfcumbxkvbrgtywduufyuieytckxhnmssqoiumuqnmyjmvojtuiofmnyqbxxoktjdirxwmomcnyqmnagkkupykrplppccjmftgeqtugvlfoxuoegbbxalppahfelrqrlxxftslrgqgelwitxluxxkpauwegoxadxairvtjcmrhaorwmermeecgybmiqkkvinecjannofwovrnixfwckyklbwvtkhpuwvxgvnvmttdrnrblwanjaavdwryjbqfxmfgksdwoyahmrixrinbknwpmrowsfettjaeefbtgebsvlspvirjvqyliqkexoxsaaweibaofbkdmftjolumctxnmkrlbrebtdiceitlmepyjjkaufnycnmoygcaaieumoysysflwwnjgajdiyeknrbmaeobmsxbjwujqcwpykbhnnkvmoiaijolpgofymglldwehtuihxpulcqytbbemspdyekasqlfwijefgnmffhsiarcbvinqyspfdrbwegtoratbniivpbervisrqjkrcaxiryfxhbpbblerumnmotfkeaewjopoqpykqglahbdkmiejurwjncvrcapoqhdjweupkgprjsevdjgydfkrhhlljbcdkhmjlhyvpqpymuxpggojlcbujnisqlvcsllfunbletmqqmjwsaggckblamhqxfuqqhxouccbvoumcelwgrejehwetgvtmsnfaltwnvblnvapcloigsrkbrpwxnrkgfsjqoihnjubfvshjhsrdkdecubbkunsaietxnblyxohvjogsjavufcyagcmbsgcbmxbaymaydhvmxegkeehkhgmnlaoeishuqjxrxarcjnqjtytaebklkayvcpcmjljcuhuvjmxscqfvqyvwdjinljlnypakbjnwtiudwswblcwcduyggjtruhhuwhhytwxnhsqenpfyteeacfgkrddmkkjkutjqqjeycwdrplslpwltfufwxklkuvwrpgigpohtmlleyfpqecllwqiwbwjxshskpbsgsbchoqlnvbecfpociybjvlkqudbkguqyvvgkmrakvembwdgfdjpywcqrftdlovnmrvyeqyqmeepbhximiaofcfahydvqylfthfaxermkvfnfdwunwjvcqvlryhiauotdvudcoqpmxdrbcorcxngolrhmcrmwgjcegghuywhwcbafqrjqhpgshnflhujoelumtchuyqrcrujkmscwkiptxvgfsrvwdrlatsuvlpxdkhoycsvobokbmqifkheoypquklsvdqbnarpeknsnegoqwavihcyitpfedychrewsvoyjduwhbobxoyivcjgvbldhkfoflnakdytitqrufsvtsgrusxstmxdwgteriecnexvxpnvwhrtaxlwqmrnyqqxwndqvhtjnthojukhecdgcqftdxjeqcfnpiglrcwiwgwgehpijsrlmwhpuqwnvcblmiagkyojglqksiseemsqkaihthvpjydxjdfwdtgjgwtbiogmcyfobnvwvrohrsgdvlabhhkpggroxadcbiqeyocwjqedjmgiahjiowaudrkdtnfuyxcxpeuyubchoirorbygxacetojoerldpndftagrciystqjltjuulwyhnivtckasadaughmkrndngoaaauultvtjhrdjedehjfcroqcigfwmtyoutkipieypwecdkgkvnmnefpnnwkcslrpfeywmdxdccfgmnqkcgxgnpvcmgegrxvycwxpdvuhycnnphytpybdpyhcgokamjcpiahlwctxgjnvsmsiovoeuvidmvecfitpkbejfajljxjdmclbxcftyqwnmdptnjlympkrpudasnffpshqvokwfhmtndnboaacrltigxkynrgfknvidihksufgxuhowkqpvlaelkfbeliqafafpjpiewoeuyttjklhxlllxqmcevtedvlufeemduqxvmsfxemxsakssyxxureapqvuwcjaybyvntdnasousyooammvgsxvlvsixdlagmvviykirygnaueajqxplynauikvnvvtitqqsdcneidefhgoafgnetnbeywsusogmhyikbxqlduqmcfmjnaphqqopojmjxsyiujuvhmimhbylhnwupmfgevvsflefgdnbmjxvviifjjtswqqnevtitsdyeheknumcemycujhgtbasusgyqdjkxojcvpolmdospnumyfvuixodqwehcnracdebuvmiydbrsygsgepocguueycinvlrypswlihnlihfjpapuphwwcsdbwlotwhupcrdkyswkaevqeolvvksxfxydkqyjavbcqhpraocbsbrypfulpqjxokdbbcnbxogovvhwklafoteeyyrqrdqhotirxxvwpcnlawkklmpagvhhwbbpfrwvmhpkiljxpalpywckltnspwcpxdffvebknrwvfjtvlgnkfsxqmnlfkowkrcqpitcxlcwtlqpyyfjgxjanwlujcruwvnmghrevtbphuhgvmrdnefbdqxnvpksnahthyafucucyekurfahjfkmyicuaonnoujywjerncwmgjiaokhaqtppcrkehatvudwtpcmdelsmubnmnwmerevtwgbgiuegbcaqeovkaowxrkmgibmagjvdrwjbuppubjwrdvjgambigmkrxwoakvoeqacbgeuigbgwtveremwnmnbumsledmcptwduvtahekrcpptqahkoaijgmwcnrejwyjuonnoauciymkfjhafrukeycucufayhthanskpvnxqdbfendrmvghuhpbtverhgmnvwurcjulwnajxgjfyypqltwclxctipqcrkwokflnmqxsfknglvtjfvwrnkbevffdxpcwpsntlkcwyplapxjlikphmvwrfpbbwhhvgapmlkkwalncpwvxxritohqdrqryyeetofalkwhvvogoxbncbbdkoxjqplufpyrbsbcoarphqcbvajyqkdyxfxskvvloeqveakwsykdrcpuhwtolwbdscwwhpupapjfhilnhilwspyrlvnicyeuugcopegsgysrbdyimvubedcarnchewqdoxiuvfymunpsodmlopvcjoxkjdqygsusabtghjucymecmunkeheydstitvenqqwstjjfiivvxjmbndgfelfsvvegfmpuwnhlybhmimhvujuiysxjmjopoqqhpanjmfcmqudlqxbkiyhmgosuswyebntengfaoghfediencdsqqtitvvnvkiuanylpxqjaeuangyrikyivvmgaldxisvlvxsgvmmaooysuosandtnvybyajcwuvqpaeruxxysskasxmexfsmvxqudmeefulvdetvecmqxlllxhlkjttyueoweipjpfafaqilebfklealvpqkwohuxgfuskhidivnkfgrnykxgitlrcaaobndntmhfwkovqhspffnsaduprkpmyljntpdmnwqytfcxblcmdjxjljafjebkptifcevmdivueovoismsvnjgxtcwlhaipcjmakogchypdbyptyhpnncyhuvdpxwcyvxrgegmcvpngxgckqnmgfccdxdmwyefprlsckwnnpfenmnvkgkdcewpyeipiktuoytmwfgicqorcfjhedejdrhjtvtluuaaaogndnrkmhguadasakctvinhywluujtljqtsyicrgatfdnpdlreojotecaxgybroriohcbuyuepxcxyufntdkrduawoijhaigmjdeqjwcoyeqibcdaxorggpkhhbalvdgsrhorvwvnbofycmgoibtwgjgtdwfdjxdyjpvhthiakqsmeesiskqlgjoykgaimlbcvnwquphwmlrsjiphegwgwiwcrlgipnfcqejxdtfqcgdcehkujohtnjthvqdnwxqqynrmqwlxatrhwvnpxvxenceiretgwdxmtsxsurgstvsfurqtitydkanlfofkhdlbvgjcviyoxbobhwudjyovswerhcydefptiychivawqogensnkepranbqdvslkuqpyoehkfiqmbkobovscyohkdxplvustalrdwvrsfgvxtpikwcsmkjurcrqyuhctmuleojuhlfnhsgphqjrqfabcwhwyuhggecjgwmrcmhrlognxcrocbrdxmpqocduvdtouaihyrlvqcvjwnuwdfnfvkmrexafhtflyqvdyhafcfoaimixhbpeemqyqeyvrmnvoldtfrqcwypjdfgdwbmevkarmkgvvyqugkbduqklvjbyicopfcebvnlqohcbsgsbpkshsxjwbwiqwllceqpfyellmthopgigprwvuklkxwfuftlwplslprdwcyejqqjtukjkkmddrkgfcaeetyfpneqshnxwtyhhwuhhurtjggyudcwclbwswduitwnjbkapynljlnijdwvyqvfqcsxmjvuhucjljmcpcvyaklkbeatytjqnjcraxrxjquhsieoalnmghkheekgexmvhdyamyabxmbcgsbmcgaycfuvajsgojvhoxylbnxteiasnukbbucedkdrshjhsvfbujnhioqjsfgkrnxwprbkrsgiolcpavnlbvnwtlafnsmtvgtewhejergwlecmuovbccuoxhqqufxqhmalbkcggaswjmqqmtelbnufllscvlqsinjubcljoggpxumypqpvyhljmhkdcbjllhhrkfdygjdvesjrpgkpuewjdhqopacrvcnjwrujeimkdbhalgqkypqopojweaekftomnmurelbbpbhxfyrixacrkjqrsivrebpviinbtarotgewbrdfpsyqnivbcraishffmngfejiwflqsakeydpsmebbtyqclupxhiuthewdllgmyfogplojiaiomvknnhbkypwcqjuwjbxsmboeambrnkeyidjagjnwwlfsysyomueiaacgyomncynfuakjjypemltiecidtberblrkmnxtcmulojtfmdkbfoabiewaasxoxekqilyqvjrivpslvsbegtbfeeajttefswormpwnkbnirxirmhayowdskgfmxfqbjyrwdvaajnawlbrnrdttmvnvgxvwuphktvwblkykcwfxinrvowfonnajcenivkkqimbygceemremwroahrmcjtvriaxdaxogewuapkxxulxtiwlegqgrlstfxxlrqrlefhapplaxbbgeouxoflvgutqegtfmjccpplprkypukkganmqyncmomwxridjtkoxxbqynmfoiutjovmjymnqumuioqssmnhxkctyeiuyfuudwytgrbvkxbmucfjnafclxjcdcwcaxujofrkfdruayhjodbjohrgshfbawgqinocworibsnoicientpgokbrfftioqcgoaimlytkijgdnmmfeeeudvuvobggayvymjsbnicftrqihgyhbgafetpgbfixmmgjsiwioimljihadphtcepvpkxbqtrasvmitmvbxccjfosjnbcenfworchnasnkcalqlryowkptypfjmwewnufbcnanomylmrrwslybjxoodgdnjhojsrbmwlmcaftnxdxpabmusgjowuwyowgernaukfikgopgbwdfgeidjopwgwsifqewcsmaxruxkqcvoytcstnliqcurychojictscxectoadaleamgluhkxdsikqwlopxtlxepaqolvxwxnrwyvepnpylycelsexpvulymrooxjexmtsgilqcquekjalcgactiqkwtcixwifelfpdusvelcyetlxlrjhjwgotfwsquxlfkuhqhtffhlggrmcilyrdapbmasepnqxtnnlajrxyttdjabnixccnngikflptbjilcrbivcvktaspdldimtdbbuulhflpfojttwklitobwfmrvjdjsigpkoxrxuelskhioqtewhoehbmmpudbuqpsodnlcrckuqlirkprxlpukogmamlcamfdythrvlvkwysymbadbynvotaxmyvwljthusslowpuloyhxyoejrvqhbynlkbemxljevsrjyvcqxstougqjuprmomhvapcrnqmkrthiwhuhwkxjlyrfadfqjpsgclfbvsdhtxnphhgnywpgxlahrpxbnhaxnmxovftendhtihvsybfqtihncqbmrnxyostrooutuxwpismhhuhegqmmwlosweevcduuruuepcdajpxdnqorryxemilaayyhjaxmfrbmqkaecgntyntlmnrlfmbsmxhwsflpyommitpfhxxlaesbhdimxdjpdbjdewdlfqubmpfsxtsyvnquffafagexwmysokqeedtsrkaxvcgbilswdryajrxeumbkglkklgqsovpstugjgavdggbfujckfnyvxcrrrubtatkkmfkdrpyblrcjemlhmudgkuoushhpfewjnudndfyanpvtxnegkgpochlbcdpsocgxpvobrjdqpipodvovdibydikgmnmqkkgnbfxyrsbxfrxfpgredqmttutvbahtgypancvqlixxaqmlbypgwravsslfrgeeklcwomqnghknnltubxgyvfhlyfblvqblupeaghbqryrsivmayypkfcilhijhtjhthwwppcwwougiulkoskyruaaymxayciurfuqqnyqgasxfrwnypyrtlawkuoekdyyofoxhyxiuxxpsfohtkpvyeigklfjmrhoxpawewhcfsykjdpwjklsruyxvnaxqrmylcoypodugvskrflqqottxjxxvijpfjkkkavugfavenyaotwwqisamplecafswinptoujbkudyedpbmbpsdmillyhbudgowujnimwlqxhbnnltvbkpxgeiccteejeikuouvwenkqprphigbclpeamvvkyuxjtpyroikmvryfji';

$result = palindromeIndex($s);
echo $result;
return;

$fptr = fopen(getenv("OUTPUT_PATH"), "w");

$stdin = fopen("php://stdin", "r");

fscanf($stdin, "%d\n", $q);

for ($q_itr = 0; $q_itr < $q; $q_itr++) {
    $s = '';
    fscanf($stdin, "%[^\n]", $s);

    $result = palindromeIndex($s);

    fwrite($fptr, $result . "\n");
}

fclose($stdin);
fclose($fptr);
